-- 034_runtime_schema_contract_closure.sql
-- Close production-reachable schema/code drift without introducing duplicate owners.

ALTER TABLE users ADD COLUMN IF NOT EXISTS activity JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "activityUpdatedAt" BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "ssoProvider" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "ssoId" TEXT;

ALTER TABLE servers ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS "featuredAt" BIGINT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS "vanityUrl" TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS "ssoConfig" JSONB;

ALTER TABLE members ADD COLUMN IF NOT EXISTS nickname TEXT;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS "modOnly" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE threads ADD COLUMN IF NOT EXISTS "firstMessage" TEXT NOT NULL DEFAULT '';
ALTER TABLE threads ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]';
ALTER TABLE threads ADD COLUMN IF NOT EXISTS "participantCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE threads ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE threads ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE voice_messages ADD COLUMN IF NOT EXISTS transcript TEXT;

ALTER TABLE messages ADD COLUMN IF NOT EXISTS transcript TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "webhookId" TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "isWebhook" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "flaggedMsgId" TEXT;

ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE webhooks ALTER COLUMN secret DROP NOT NULL;
UPDATE webhooks SET token = secret WHERE token IS NULL AND secret IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_webhooks_token ON webhooks(token) WHERE token IS NOT NULL;
