process.env.NODE_ENV='test'; process.env.JWT_SECRET='12345678901234567890123456789012'; process.env.REFRESH_SECRET='12345678901234567890123456789012';
jest.mock('../db/loader',()=>require('./helpers/mockDb').createMockDb());
jest.mock('../db/postgres/transaction',()=>({withTransaction:async(fn:any)=>fn({query:async()=>({rows:[]})})}));
jest.mock('../middleware/rateLimit',()=>({limits:{messages:()=> (_req:any,_res:any,next:any)=>next(),dm:()=> (_req:any,_res:any,next:any)=>next()}}));
import express from 'express'; import request from 'supertest'; import jwt from 'jsonwebtoken'; import db from '../db/loader'; import router from '../routes/groupDm';
import { GroupDms } from '../db/repositories';
import { requireDoc } from './helpers/mockDb';
const secret=process.env.JWT_SECRET!; const token=(id:string)=>jwt.sign({id,v:0},secret,{expiresIn:'1h'});
const auth=(r:any,id:string)=>r.set('Authorization',`Bearer ${token(id)}`);
function app(io:any=null){const a=express();a.set('io',io);a.use(express.json());a.use('/api/gdm',router);return a;}
async function user(id:string,name=id){await db.users.insert({_id:id,username:name,displayName:name,tokenVersion:0});}
async function group(id='g1',owner='u1'){await db.groupDmConversations.insert({_id:id,name:'G',ownerId:owner,createdAt:1,lastMessageAt:1});}
async function member(g:string,u:string,extra:any={}){await db.groupDmMembers.insert({_id:`${g}-${u}`,groupId:g,userId:u,joinedAt:1,...extra});}
function ioMock(withRooms=true){const emit=jest.fn();const socketsLeave=jest.fn(),socketsJoin=jest.fn();return {emit,socketsLeave,socketsJoin,io:{to:jest.fn(()=>({emit})),...(withRooms?{in:jest.fn(()=>({socketsLeave,socketsJoin}))}:{})}};}

describe('GDM route branch behavior',()=>{
 beforeEach(()=>db._reset?.());
 afterEach(()=>jest.restoreAllMocks());
 test('list skips stale memberships and sorts by last activity with unread metadata',async()=>{await user('u1'); await group('old','u1'); await group('new','u1'); await db.groupDmConversations.update({_id:'new'},{$set:{lastMessageAt:20}}); await member('old','u1',{readAt:0}); await member('new','u1',{readAt:0}); await db.groupDmMembers.insert({_id:'stale',groupId:'missing',userId:'u1',joinedAt:1}); await db.groupDmMessages.insert({_id:'m',groupId:'new',userId:'u2',type:'text',createdAt:10}); const r=await auth(request(app()).get('/api/gdm'),'u1'); expect(r.status).toBe(200); expect(r.body.map((x:any)=>x._id)).toEqual(['new','old']); expect(r.body[0].unreadCount).toBe(1);});
 test('detail enforces existence and membership and enriches success',async()=>{await user('u1'); expect((await auth(request(app()).get('/api/gdm/nope'),'u1')).status).toBe(404); await group(); expect((await auth(request(app()).get('/api/gdm/g1'),'u1')).status).toBe(403); await member('g1','u1'); expect((await auth(request(app()).get('/api/gdm/g1'),'u1')).status).toBe(200);});
 test('patch enforces owner and fields, supports name/icon and emits to members',async()=>{await user('u1');await user('u2');await group();await member('g1','u1');await member('g1','u2'); expect((await auth(request(app()).patch('/api/gdm/nope').send({name:'x'}),'u1')).status).toBe(404); expect((await auth(request(app()).patch('/api/gdm/g1').send({}),'u2')).status).toBe(403); await member('g1','u2').catch(()=>{}); expect((await auth(request(app()).patch('/api/gdm/g1').send({}),'u1')).status).toBe(400); const iom=ioMock(); const r=await auth(request(app(iom.io)).patch('/api/gdm/g1').send({name:'  Renamed  ',icon:''}),'u1'); expect(r.status).toBe(200); expect(r.body.name).toBe('Renamed'); expect(r.body.icon).toBeNull(); expect(iom.emit).toHaveBeenCalledWith('gdm:updated',expect.anything());});
 test('delete requires member owner and notifies all members',async()=>{await user('u1');await user('u2'); expect((await auth(request(app()).delete('/api/gdm/nope'),'u1')).status).toBe(404); await group(); expect((await auth(request(app()).delete('/api/gdm/g1'),'u1')).status).toBe(403); await member('g1','u1');await member('g1','u2'); expect((await auth(request(app()).delete('/api/gdm/g1'),'u2')).status).toBe(403); const iom=ioMock(); const r=await auth(request(app(iom.io)).delete('/api/gdm/g1'),'u1'); expect(r.status).toBe(200); expect(await db.groupDmConversations.findOne({_id:'g1'})).toBeNull(); expect(iom.emit).toHaveBeenCalledTimes(2);});
 test('add-member validation covers nonowner, missing id, duplicate, cap and missing user',async()=>{await user('u1');await user('u2');await group();await member('g1','u1');await member('g1','u2'); expect((await auth(request(app()).post('/api/gdm/g1/members').send({userId:'x'}),'u2')).status).toBe(403); expect((await auth(request(app()).post('/api/gdm/g1/members').send({}),'u1')).status).toBe(400); expect((await auth(request(app()).post('/api/gdm/g1/members').send({userId:'u2'}),'u1')).status).toBe(409); expect((await auth(request(app()).post('/api/gdm/g1/members').send({userId:'missing'}),'u1')).status).toBe(404); for(let i=3;i<=20;i++){await user(`u${i}`);await member('g1',`u${i}`);} await user('u21'); expect((await auth(request(app()).post('/api/gdm/g1/members').send({userId:'u21'}),'u1')).status).toBe(429);});
 test('add-member success joins room and broadcasts sanitized member',async()=>{await user('u1','owner');await user('u2','newbie');await user('u3','other');await group();await member('g1','u1');await member('g1','u3');const iom=ioMock();const r=await auth(request(app(iom.io)).post('/api/gdm/g1/members').send({userId:'u2'}),'u1');expect(r.status).toBe(200);expect(iom.socketsJoin).toHaveBeenCalledWith('gdm:g1');expect(iom.emit).toHaveBeenCalledWith('gdm:member:join',expect.objectContaining({groupId:'g1',user:expect.objectContaining({_id:'u2'})}));});
 test('member removal enforces actor/owner and last-member deletion',async()=>{await user('u1');await user('u2');await user('u3');await group();await member('g1','u1');await member('g1','u2');await member('g1','u3'); expect((await auth(request(app()).delete('/api/gdm/g1/members/u1'),'u2')).status).toBe(403); expect((await auth(request(app()).delete('/api/gdm/g1/members/u1'),'u3')).status).toBe(403); expect((await auth(request(app()).delete('/api/gdm/g1/members/u1'),'u2')).status).toBe(403); const r=await auth(request(app()).delete('/api/gdm/g1/members/u2'),'u1');expect(r.status).toBe(200); expect(await db.groupDmMembers.findOne({groupId:'g1',userId:'u2'})).toBeNull();});
 test('member removal never reports success or writes a system message for a non-member',async()=>{await user('u1');await user('u2');await group();await member('g1','u1');const before=await db.groupDmMessages.count({groupId:'g1'});const r=await auth(request(app()).delete('/api/gdm/g1/members/u2'),'u1');expect(r.status).toBe(404);expect(await db.groupDmMessages.count({groupId:'g1'})).toBe(before);});
 test('member removal rejects malformed target identifiers before repository mutation',async()=>{await user('u1');await group();await member('g1','u1');const remove=jest.spyOn(GroupDms,'removeMember');const r=await auth(request(app()).delete(`/api/gdm/g1/members/${'x'.repeat(129)}`),'u1');expect(r.status).toBe(400);expect(remove).not.toHaveBeenCalled();});
 test('owner self-leave transfers ownership; sole owner leave deletes group and leaves socket rooms',async()=>{await user('u1');await user('u2');await group();await member('g1','u1');await member('g1','u2');const iom=ioMock();let r=await auth(request(app(iom.io)).delete('/api/gdm/g1/members/u1'),'u1');expect(r.status).toBe(200);expect((await db.groupDmConversations.findOne({_id:'g1'}))?.ownerId).toBe('u2');expect(iom.socketsLeave).toHaveBeenCalledWith('gdm:g1'); await db._reset?.();await user('u1');await group();await member('g1','u1');r=await auth(request(app()).delete('/api/gdm/g1/members/u1'),'u1');expect(r.status).toBe(200);expect(await db.groupDmConversations.findOne({_id:'g1'})).toBeNull();});
 test('message history enforces membership, cursor bounds and marks read',async()=>{await user('u1');await group(); expect((await auth(request(app()).get('/api/gdm/g1/messages'),'u1')).status).toBe(403);await member('g1','u1');await db.groupDmMessages.insert({_id:'m1',groupId:'g1',userId:'u2',type:'text',createdAt:10,content:'x'});let r=await auth(request(app()).get('/api/gdm/g1/messages?limit=999&before=20&beforeId=m1'),'u1');expect(r.status).toBe(200);expect(r.body).toHaveLength(1);expect(typeof (await db.groupDmMembers.findOne({groupId:'g1',userId:'u1'}))?.readAt).toBe('number');r=await auth(request(app()).get('/api/gdm/g1/messages?beforeId='+('x'.repeat(100))),'u1');expect(r.status).toBe(200);});
 test('message history is not returned when membership is revoked while the read is in flight',async()=>{await user('u1');await user('u2');await group();await member('g1','u1');await db.groupDmMessages.insert({_id:'secret',groupId:'g1',userId:'u2',type:'text',createdAt:10,content:'private'});const canonical=GroupDms.findMember.bind(GroupDms);let checks=0;jest.spyOn(GroupDms,'findMember').mockImplementation(async(gid,uid)=>{checks+=1;if(checks===1)return canonical(gid,uid);await db.groupDmMembers.remove({groupId:gid,userId:uid});return null;});const r=await auth(request(app()).get('/api/gdm/g1/messages'),'u1');expect(r.status).toBe(403);expect(JSON.stringify(r.body)).not.toContain('private');});
 test('message history rejects negative, fractional and unsafe numeric pagination input',async()=>{await user('u1');await group();await member('g1','u1');for(const q of ['limit=-1','limit=1.5','limit=9007199254740992','before=-1','before=1.5','before=9007199254740992']){const r=await auth(request(app()).get(`/api/gdm/g1/messages?${q}`),'u1');expect(r.status).toBe(400);}});
 test('message send validation and broadcast paths',async()=>{await user('u1');await user('u2');await group();await member('g1','u1');await member('g1','u2'); expect((await auth(request(app()).post('/api/gdm/g1/messages').send({content:'   '}),'u1')).status).toBe(400);expect((await auth(request(app()).post('/api/gdm/g1/messages').send({content:'x'.repeat(2001)}),'u1')).status).toBe(400);expect((await auth(request(app()).post('/api/gdm/nope/messages').send({content:'x'}),'u1')).status).toBe(404);const iom=ioMock();const r=await auth(request(app(iom.io)).post('/api/gdm/g1/messages').send({content:' hi '}),'u1');expect(r.status).toBe(201);expect(r.body.content).toBe('hi');expect(iom.emit).toHaveBeenCalledWith('inbox:changed',{reason:'gdm'});});
});

describe('GDM runtime body type validation', () => {
 beforeEach(()=>db._reset?.());
 test('create rejects malformed JSON types without throwing',async()=>{await user('u1');await user('u2');for(const body of [
   {name:7,memberIds:['u2']},{name:'G',memberIds:'u2'},{name:'G',memberIds:[7]},{name:'G',memberIds:['']},{name:'G',memberIds:['u2'],icon:7}
 ]){const r=await auth(request(app()).post('/api/gdm').send(body),'u1');expect(r.status).toBe(400);}});
 test('patch rejects non-string or blank mutable fields',async()=>{await user('u1');await group();await member('g1','u1');for(const body of [{name:7},{name:'   '},{icon:7}]){const r=await auth(request(app()).patch('/api/gdm/g1').send(body),'u1');expect(r.status).toBe(400);}});
 test('add-member rejects non-string, blank and overlong ids',async()=>{await user('u1');await group();await member('g1','u1');for(const userId of [7,'','x'.repeat(129)]){const r=await auth(request(app()).post('/api/gdm/g1/members').send({userId}),'u1');expect(r.status).toBe(400);}});
 test('message send rejects non-string content instead of invoking string methods',async()=>{await user('u1');await group();await member('g1','u1');for(const content of [7,{},[]]){const r=await auth(request(app()).post('/api/gdm/g1/messages').send({content}),'u1');expect(r.status).toBe(400);}});
});
