process.env.NODE_ENV='test';process.env.JWT_SECRET='12345678901234567890123456789012';
import {createMockDb} from './helpers/mockDb';const mockDb=createMockDb();// Ikizler URUN imzalarindan tiplenir: yayilimla cagrildiklari icin rest
// parametreleri, cagri kaydindan okunduklari icin de dogru demet tipleri
// gerekiyor.
const push=jest.fn<Promise<void>, [userId: string, payload: Record<string, unknown>]>(async()=>undefined);
const cacheGet=jest.fn<Promise<unknown>, unknown[]>(),cacheSet=jest.fn<Promise<unknown>, unknown[]>();
const canView=jest.fn<Promise<boolean>, unknown[]>(async()=>true);
jest.mock('../db/loader',()=>mockDb);jest.mock('../lib/pushSender',()=>({sendPushToUser:(userId: string, payload: Record<string, unknown>) =>push(userId, payload)}));jest.mock('../lib/redisAdapter',()=>({cache:{get:(...a: unknown[]) =>cacheGet(...a),set:(...a: unknown[]) =>cacheSet(...a),invalidatePattern:jest.fn(),delete:jest.fn()}}));jest.mock('../lib/permissions',()=>{const actual=jest.requireActual('../lib/permissions');return {...actual,canViewChannel:(...a: unknown[]) =>canView(...a)}});
import express from 'express';import request from 'supertest';import jwt from 'jsonwebtoken';import {Notifications} from '../db/repositories';import {processNotifications,extractMentions,extractDirectMentionIds,incrementUnread,clearUnread,getUnreadCounts,getNotifPref,deliverPushBatched,__pendingPushForTest,__PUSH_DEBOUNCE_MS,__PUSH_MAX_WAIT_MS,__PUSH_KEEP_MSGS,pushRouter} from '../lib/notifications';
function io(){const emitted:any[]=[];return{emitted,to:(target:string)=>({emit:(event:string,data:any)=>emitted.push({target,event,data})})};}
async function seed(){await mockDb.users.insert({_id:'sender',username:'sender'});await mockDb.users.insert({_id:'u1',username:'alice',tokenVersion:0});await mockDb.users.insert({_id:'u2',username:'bob'});await mockDb.servers.insert({_id:'s1',ownerId:'sender'});await mockDb.channels.insert({_id:'c1',serverId:'s1',name:'general'});for(const u of ['sender','u1','u2'])await mockDb.members.insert({userId:u,serverId:'s1',roles:[]});}
const msg=(content:string,id='m1')=>({_id:id,content,channelId:'c1',serverId:'spoofed',userId:'sender',displayName:'Sender',createdAt:10});
describe('notifications core branches',()=>{beforeEach(async()=>{mockDb._reset();jest.clearAllMocks();__pendingPushForTest.clear();canView.mockResolvedValue(true);cacheGet.mockResolvedValue(null);cacheSet.mockResolvedValue(undefined);await seed();});afterEach(()=>{for(const p of __pendingPushForTest.values()){if(p.timer) clearTimeout(p.timer);}__pendingPushForTest.clear();jest.clearAllTimers();jest.useRealTimers();});
 test('mention extractors dedupe, lowercase and exclude everyone/here',()=>{expect(extractMentions('@Alice @alice @everyone @here @Bob')).toEqual(['alice','bob']);expect(extractDirectMentionIds('<@u1> <@u1> <@u-2>')).toEqual(['u1','u-2']);});
 test('no mention, missing channel, and channel without server short-circuit',async()=>{const x=io();await processNotifications(msg('hello'),x,new Map());expect(x.emitted).toHaveLength(0);await mockDb.channels.remove({_id:'c1'});await processNotifications(msg('@alice'),x,new Map());expect(x.emitted).toHaveLength(0);await mockDb.channels.insert({_id:'c1',name:'x'});await processNotifications(msg('@alice'),x,new Map());expect(x.emitted).toHaveLength(0);});
 test('everyone mention targets current members except sender/excluded and canonical server',async()=>{const x=io();const sockets=new Map();await processNotifications(msg('@everyone'),x,sockets,new Set(['u2']));expect(await mockDb.notifications.find({userId:'u1'})).toHaveLength(1);expect(await mockDb.notifications.find({userId:'u2'})).toHaveLength(0);expect(canView).toHaveBeenCalledWith('u1','s1','c1');expect(x.emitted).toEqual(expect.arrayContaining([expect.objectContaining({target:'user:u1',event:'notification:mention'}),expect.objectContaining({target:'user:u1',event:'inbox:changed'})]));});
 test('regular/direct mentions only target server members and dedupe recipients',async()=>{await mockDb.users.insert({_id:'outside',username:'outside'});const x=io();await processNotifications(msg('@alice <@u1> @outside'),x,new Map());expect(await mockDb.notifications.find({userId:'u1'})).toHaveLength(1);expect(await mockDb.notifications.find({userId:'outside'})).toHaveLength(0);});
 test('visibility, mute and mentions preference filters fail closed',async()=>{canView.mockImplementation(async(...args: unknown[])=>args[0]!=='u2');await Notifications.upsertPref('u1','c1',{level:'mute',muteUntil:null});await processNotifications(msg('@alice @bob'),io(),new Map());expect(await mockDb.notifications.find({})).toHaveLength(0);await Notifications.upsertPref('u1','c1',{level:'mentions'});await processNotifications(msg('@everyone','m2'),io(),new Map());expect(await mockDb.notifications.find({userId:'u1'})).toHaveLength(1);});
test('preference-store failure suppresses mentions instead of treating everyone as unmuted',async()=>{jest.spyOn(Notifications,'prefsFind').mockImplementationOnce(()=>Promise.reject(new Error('prefs down')) as any);const x=io();await expect(processNotifications(msg('@alice'),x,new Map())).resolves.toBeUndefined();expect(await mockDb.notifications.find({})).toHaveLength(0);expect(x.emitted).toHaveLength(0);expect(push).not.toHaveBeenCalled();});
 test('idempotent insert false prevents duplicate realtime/push/unread',async()=>{const ins=jest.spyOn(Notifications,'insertChannelAttention').mockResolvedValueOnce(false);const x=io();await processNotifications(msg('@alice'),x,new Map([['s',{id:'u1'}]]));expect(ins).toHaveBeenCalled();expect(x.emitted).toHaveLength(0);expect(push).not.toHaveBeenCalled();expect(await mockDb.unreadCounts.find({})).toHaveLength(0);});
 test('one target failure is isolated by allSettled',async()=>{jest.spyOn(Notifications,'insertChannelAttention').mockRejectedValueOnce(new Error('db'));await expect(processNotifications(msg('@alice @bob'),io(),new Map())).resolves.toBeUndefined();expect(await mockDb.notifications.find({userId:'u2'})).toHaveLength(1);});
 test('incrementUnread uses atomic PG owner when it wins and fallback insert/update otherwise',async()=>{const atom=jest.spyOn(Notifications,'unreadIncrementAtomic').mockResolvedValueOnce(true);await incrementUnread('u1','c1');expect(atom).toHaveBeenCalled();expect(await mockDb.unreadCounts.find({})).toHaveLength(0);atom.mockResolvedValue(false);await incrementUnread('u1','c1');await incrementUnread('u1','c1');expect((await mockDb.unreadCounts.findOne({userId:'u1',channelId:'c1'}))?.count).toBe(2);});
 test('clear/get unread tolerate repository failures and return canonical map',async()=>{await mockDb.unreadCounts.insert({_id:'a',userId:'u1',channelId:'c1',count:3});await clearUnread('u1','c1');expect((await mockDb.unreadCounts.findOne({_id:'a'}))?.count).toBe(0);jest.spyOn(Notifications,'unreadUpdate').mockRejectedValueOnce(new Error('db'));await expect(clearUnread('u1','c1')).resolves.toBeUndefined();jest.spyOn(Notifications,'unreadFind').mockReturnValueOnce(Promise.resolve([{channelId:'c1',count:2,userId:'u1'}]) as any);expect(await getUnreadCounts('u1')).toEqual({c1:2});jest.spyOn(Notifications,'unreadFind').mockImplementationOnce(()=>{throw new Error('db')});expect(await getUnreadCounts('u1')).toEqual({});});
 test('getNotifPref uses cache hit and DB miss/default with TTL write',async()=>{cacheGet.mockResolvedValueOnce('mute');expect(await getNotifPref('u1','c1')).toBe('mute');expect(cacheSet).not.toHaveBeenCalled();cacheGet.mockResolvedValueOnce(null);await Notifications.upsertPref('u1','c1',{level:'mentions'});expect(await getNotifPref('u1','c1')).toBe('mentions');expect(cacheSet).toHaveBeenCalledWith('notifpref:u1:c1','mentions',120);cacheGet.mockResolvedValueOnce(null);expect(await getNotifPref('u2','c1')).toBe('all');});
 test('push batching sends one and bounded multi-message payload without unbounded buffer',async()=>{jest.useFakeTimers();deliverPushBatched('u1',msg('one'));expect(__pendingPushForTest.get('u1:c1')?.count).toBe(1);await jest.advanceTimersByTimeAsync(__PUSH_DEBOUNCE_MS);expect(push).toHaveBeenCalledTimes(1);push.mockClear();for(let i=0;i<8;i++){deliverPushBatched('u1',{...msg('x'+i,'m'+i),displayName:'S'});await jest.advanceTimersByTimeAsync(100);}const p=__pendingPushForTest.get('u1:c1')!;expect(p.count).toBe(8);expect(p.msgs.length).toBe(__PUSH_KEEP_MSGS);await jest.advanceTimersByTimeAsync(__PUSH_MAX_WAIT_MS);expect(push).toHaveBeenCalledTimes(1);expect(push.mock.calls[0][1].title).toContain('8 yeni mention');});
 test('push router validates, de-duplicates subscriptions and owns unsubscribe/vapid/native token contracts',async()=>{const a=express();a.use(express.json());a.use('/push',pushRouter);const bearer=`Bearer ${jwt.sign({id:'u1',v:0},process.env.JWT_SECRET!,{expiresIn:'1h'})}`;const sub={endpoint:'https://push.example.com/e1',keys:{p256dh:'x',auth:'y'}};let r=await request(a).post('/push/subscribe').set('Authorization',bearer).send({subscription:{}});expect(r.status).toBe(400);r=await request(a).post('/push/subscribe').set('Authorization',bearer).send({subscription:sub});expect(r.body.subscribed).toBe(true);r=await request(a).post('/push/subscribe').set('Authorization',bearer).send({subscription:{...sub,keys:{p256dh:'new',auth:'new-auth'}}});expect(r.body.subscribed).toBe(true);expect(await mockDb.pushSubscriptions.count({endpoint:sub.endpoint})).toBe(1);expect((await mockDb.pushSubscriptions.findOne({endpoint:sub.endpoint}))?.keys).toEqual({p256dh:'new',auth:'new-auth'});r=await request(a).post('/push/subscribe').set('Authorization',bearer).send({subscription:{endpoint:'https://127.0.0.1/private',keys:{p256dh:'x',auth:'y'}}});expect(r.status).toBe(400);r=await request(a).delete('/push/unsubscribe').set('Authorization',bearer).send({endpoint:sub.endpoint});expect(r.body.unsubscribed).toBe(true);process.env.VAPID_PUBLIC_KEY='pub';r=await request(a).get('/push/vapid-key');expect(r.body.publicKey).toBe('pub');delete process.env.VAPID_PUBLIC_KEY;r=await request(a).post('/push/register-native').set('Authorization',bearer).send({});expect(r.status).toBe(400);r=await request(a).post('/push/register-native').set('Authorization',bearer).send({token:'t',platform:'weird'});expect(r.status).toBe(200);expect((await mockDb.nativePushTokens.findOne({userId:'u1'}))?.platform).toBe('unknown');});
});
