process.env.NODE_ENV='test';process.env.JWT_SECRET='12345678901234567890123456789012';process.env.REFRESH_SECRET='12345678901234567890123456789012';
jest.mock('../db/loader',()=>require('./helpers/mockDb').createMockDb());
jest.mock('../middleware/rateLimit',()=>({limits:{messages:()=> (_q:any,_s:any,n:any)=>n(),general:()=> (_q:any,_s:any,n:any)=>n()}}));
import express from 'express';import request from 'supertest';import jwt from 'jsonwebtoken';import db from '../db/loader';import router from '../routes/notificationPrefs';import {Notifications} from '../db/repositories';import {PERMS} from '../lib/permissions';
const token=(id:string)=>jwt.sign({id,v:0},process.env.JWT_SECRET!,{expiresIn:'1h'});function app(){const a=express();a.use(express.json());a.use('/api/notification-prefs',router);return a;}const auth=(r:any,id='u1')=>r.set('Authorization',`Bearer ${token(id)}`);
async function seedOwner(){await db.users.insert({_id:'u1',username:'u1',tokenVersion:0});await db.servers.insert({_id:'s1',name:'S',ownerId:'u1'});await db.members.insert({userId:'u1',serverId:'s1',roles:[]});await db.channels.insert({_id:'c1',serverId:'s1',name:'c',type:'text'});}
describe('notification prefs route',()=>{beforeEach(async()=>{db._reset?.();jest.restoreAllMocks();await seedOwner();});
 test('GET requires serverId and returns channel/server preferences with default fallback',async()=>{expect((await auth(request(app()).get('/api/notification-prefs'))).status).toBe(400);let r=await auth(request(app()).get('/api/notification-prefs?serverId=s1'));expect(r.status).toBe(200);expect(r.body).toEqual({channels:[],serverLevel:'default',serverMuteUntil:null,watchWords:[]});jest.spyOn(Notifications,'findPrefsForUserInServer').mockResolvedValueOnce([{userId:'u1',channelId:'c1',level:'mentions'}] as any);jest.spyOn(Notifications,'findServerPref').mockResolvedValueOnce({level:'mute'} as any);r=await auth(request(app()).get('/api/notification-prefs?serverId=s1'));expect(r.body.serverLevel).toBe('mute');expect(r.body.channels).toHaveLength(1);});
 test('GET does not fabricate defaults when preference storage is unavailable',async()=>{jest.spyOn(Notifications,'findPrefsForUserInServer').mockRejectedValueOnce(new Error('db'));const r=await auth(request(app()).get('/api/notification-prefs?serverId=s1'));expect(r.status).toBe(503);expect(r.body).toEqual({error:'Notification preferences unavailable'});});
 test('unread returns empty, filters stale/deleted channels and totals visible rows',async()=>{let r=await auth(request(app()).get('/api/notification-prefs/unread'));expect(r.body).toEqual({channels:[],total:0});await db.unreadCounts.insert({_id:'a',userId:'u1',channelId:'missing',count:9});await db.unreadCounts.insert({_id:'b',userId:'u1',channelId:'c1',count:3});await db.unreadCounts.insert({_id:'z',userId:'u1',channelId:'c1',count:0});r=await auth(request(app()).get('/api/notification-prefs/unread'));expect(r.body).toEqual({channels:[{channelId:'c1',count:3}],total:3});});
 test('unread hides channel after VIEW_CHANNELS revoke and hides muted channels',async()=>{await db.unreadCounts.insert({_id:'b',userId:'u1',channelId:'c1',count:4});await Notifications.upsertPref('u1','c1',{level:'mute',muteUntil:null});let r=await auth(request(app()).get('/api/notification-prefs/unread'));expect(r.body.total).toBe(0);await Notifications.upsertPref('u1','c1',{level:'all'});const viewer='u2';await db.users.insert({_id:viewer,username:'u2',tokenVersion:0});const role='r1';await db.roles.insert({_id:role,serverId:'s1',name:'deny',position:1,permissions:0});await db.members.insert({userId:viewer,serverId:'s1',roles:[role]});await db.unreadCounts.insert({_id:'v',userId:viewer,channelId:'c1',count:5});r=await auth(request(app()).get('/api/notification-prefs/unread'),viewer);expect(r.body.total).toBe(0);});
 test('unread fail-closed on query failure',async()=>{jest.spyOn(Notifications,'unreadFind').mockImplementationOnce(()=>{throw new Error('db');});const r=await auth(request(app()).get('/api/notification-prefs/unread'));expect(r.body).toEqual({channels:[],total:0});});
test('unread fails closed when mute policy storage is unavailable',async()=>{await db.unreadCounts.insert({_id:'b',userId:'u1',channelId:'c1',count:4});jest.spyOn(Notifications,'findPrefsForUser').mockRejectedValueOnce(new Error('prefs down'));const r=await auth(request(app()).get('/api/notification-prefs/unread'));expect(r.status).toBe(200);expect(r.body).toEqual({channels:[],total:0});});
 test('channel pref validates input and canonical mute semantics',async()=>{expect((await auth(request(app()).put('/api/notification-prefs').send({level:'all'}))).status).toBe(400);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'bad'}))).status).toBe(400);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'mute',muteUntil:'bad'}))).status).toBe(400);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'mute',muteUntil:-1}))).status).toBe(400);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'mute',muteUntil:1.5}))).status).toBe(400);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'mute',muteUntil:9007199254740992}))).status).toBe(400);let r=await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'mute'}));expect(r.status).toBe(200);expect(r.body.muteUntil).toBeNull();r=await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'mute',muteUntil:123}));expect(r.body.muteUntil).toBe(123);r=await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'all',muteUntil:123}));expect(r.body.muteUntil).toBeNull();});
 test('server pref validates and persists namespace; delete is idempotent even on repository failure',async()=>{expect((await auth(request(app()).put('/api/notification-prefs/server').send({level:'all'}))).status).toBe(400);expect((await auth(request(app()).put('/api/notification-prefs/server').send({serverId:'s1',level:'bad'}))).status).toBe(400);let r=await auth(request(app()).put('/api/notification-prefs/server').send({serverId:'s1',level:'mentions'}));expect(r.status).toBe(200);expect((await Notifications.findServerPref('u1','s1'))?.level).toBe('mentions');await Notifications.upsertPref('u1','c1',{level:'all'});r=await auth(request(app()).delete('/api/notification-prefs/c1'));expect(r.body.deleted).toBe(true);expect(await Notifications.findPref('u1','c1')).toBeNull();jest.spyOn(Notifications,'deletePref').mockRejectedValueOnce(new Error('db'));r=await auth(request(app()).delete('/api/notification-prefs/c1'));expect(r.status).toBe(503);});
 test('preference reads/writes require current tenant authority and channel visibility',async()=>{await db.users.insert({_id:'u2',username:'u2',tokenVersion:0});expect((await auth(request(app()).get('/api/notification-prefs?serverId=s1'),'u2')).status).toBe(403);expect((await auth(request(app()).put('/api/notification-prefs/server').send({serverId:'s1',level:'all'}),'u2')).status).toBe(403);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'c1',level:'all'}),'u2')).status).toBe(403);expect((await auth(request(app()).put('/api/notification-prefs').send({channelId:'missing',level:'all'}))).status).toBe(404);});
 test('server-level persistence uses only the canonical namespace columns and GET normalizes dirty levels fail-closed',async()=>{const upsert=jest.spyOn(Notifications,'upsertPref');let r=await auth(request(app()).put('/api/notification-prefs/server').send({serverId:'s1',level:'mentions'}));expect(r.status).toBe(200);expect(upsert).toHaveBeenCalledWith('u1','server:s1',expect.objectContaining({level:'mentions'}));const payload=upsert.mock.calls.at(-1)?.[2] as Record<string,unknown>;expect(payload).not.toHaveProperty('serverId');expect(payload).not.toHaveProperty('isServerLevel');jest.restoreAllMocks();jest.spyOn(Notifications,'findPrefsForUserInServer').mockResolvedValueOnce([{userId:'u1',channelId:'c1',level:'corrupt'}] as any);jest.spyOn(Notifications,'findServerPref').mockResolvedValueOnce({level:'corrupt'} as any);r=await auth(request(app()).get('/api/notification-prefs?serverId=s1'));expect(r.status).toBe(200);expect(r.body.channels[0].level).toBe('mute');expect(r.body.serverLevel).toBe('mute');});
});
