process.env.NODE_ENV='test'; process.env.JWT_SECRET='12345678901234567890123456789012'; process.env.REFRESH_SECRET='12345678901234567890123456789012';
jest.mock('../db/loader',()=>require('./helpers/mockDb').createMockDb());
const store={uploadFile:jest.fn(),deleteFile:jest.fn(async()=>{}),keyFromUrl:jest.fn((u:string)=>u.split('/').pop()),listFiles:jest.fn(),healthCheck:jest.fn()};
jest.mock('../lib/storageAdapter',()=>({getPrivateStorageAdapter:()=>store}));
import express from 'express'; import request from 'supertest'; import jwt from 'jsonwebtoken'; import db from '../db/loader'; import router from '../routes/voicemsg'; import {Messages,VoiceMessages} from '../db/repositories'; import fs from 'fs'; import os from 'os'; import path from 'path';
const T=fs.mkdtempSync(path.join(os.tmpdir(),'bridge-vm-deep-'));const WEBM=path.join(T,'a.webm');fs.writeFileSync(WEBM,Buffer.from([0x1a,0x45,0xdf,0xa3,1,2,3]));
const tok=(id:string)=>jwt.sign({id,v:0},process.env.JWT_SECRET!,{expiresIn:'1h'});function app(io:any=null){const a=express();a.set('io',io);a.use('/api/voice-messages',router);return a;}
async function seed(){await db.users.insert({_id:'u1',username:'u1',displayName:'U1',tokenVersion:0});await db.servers.insert({_id:'s1',ownerId:'u1',name:'S'});await db.members.insert({userId:'u1',serverId:'s1',roles:[]});await db.channels.insert({_id:'c1',serverId:'s1',name:'c',type:'text'});}
function post(a:any){return request(a).post('/api/voice-messages').set('Authorization',`Bearer ${tok('u1')}`).field('channelId','c1').field('serverId','s1').field('duration','0').attach('audio',WEBM,{contentType:'audio/webm'});}
describe('voice message failure/privacy branches',()=>{
 beforeEach(async()=>{db._reset?.();jest.restoreAllMocks();store.uploadFile.mockReset().mockResolvedValue({url:'https://private.test/uploads/x.webm',key:'uploads/x.webm',provider:'s3'});store.deleteFile.mockClear();store.keyFromUrl.mockClear();delete process.env.GROQ_API_KEY;delete process.env.OPENAI_API_KEY;await seed();}); afterAll(()=>fs.rmSync(T,{recursive:true,force:true}));
 test('transcript endpoint distinguishes missing channel, pending and done',async()=>{await db.voiceMessages.insert({_id:'v1',channelId:'c1',serverId:'s1',userId:'u1',url:'/uploads/x'});let r=await request(app()).get('/api/voice-messages/v1/transcript').set('Authorization',`Bearer ${tok('u1')}`);expect(r.status).toBe(200);expect(r.body).toEqual({transcript:null,status:'pending'});await db.voiceMessages.update({_id:'v1'},{$set:{transcript:'hello'}});r=await request(app()).get('/api/voice-messages/v1/transcript').set('Authorization',`Bearer ${tok('u1')}`);expect(r.body).toEqual({transcript:'hello',status:'done'});await db.channels.remove({_id:'c1'});r=await request(app()).get('/api/voice-messages/v1/transcript').set('Authorization',`Bearer ${tok('u1')}`);expect(r.status).toBe(404);});
 test('remote successful upload persists zero duration and removes transcription copy',async()=>{const r=await post(app());expect(r.status).toBe(200);expect(r.body.vmId).toBeTruthy();const vm:any=await db.voiceMessages.findOne({_id:r.body.vmId});expect(vm.duration).toBe(0);await new Promise(r=>setTimeout(r,20));const [local]=store.uploadFile.mock.calls[0];expect(fs.existsSync(String(local))).toBe(false);});
 test('voice-row persistence failure deletes remote object',async()=>{jest.spyOn(VoiceMessages,'insert').mockResolvedValueOnce(null as any);const r=await post(app());expect(r.status).toBe(500);expect(store.deleteFile).toHaveBeenCalledWith('uploads/x.webm');});
 test('message persistence failure rolls back voice row then deletes object',async()=>{jest.spyOn(Messages,'create').mockResolvedValueOnce(null as any);const remove=jest.spyOn(VoiceMessages,'remove');const r=await post(app());expect(r.status).toBe(500);expect(remove).toHaveBeenCalled();expect(store.deleteFile).toHaveBeenCalledWith('uploads/x.webm');});
 test('DB rollback uncertainty preserves remote object fail-closed',async()=>{jest.spyOn(Messages,'create').mockResolvedValueOnce(null as any);jest.spyOn(VoiceMessages,'remove').mockRejectedValueOnce(new Error('db down'));const r=await post(app());expect(r.status).toBe(500);expect(store.deleteFile).not.toHaveBeenCalled();});
 test('storage upload failure leaves no DB references',async()=>{store.uploadFile.mockRejectedValueOnce(new Error('s3 down'));const r=await post(app());expect(r.status).toBe(500);expect(await db.voiceMessages.count({})).toBe(0);expect(await db.messages.count({})).toBe(0);});
});
